### ISSUE TITLE
指纹识别Python版本判断出错

### ISSUE THREAD

**Issue by gyunlyun** [foyaga/IntegSearch#1]
**module.Finger.lib.checkenv.CheckEnv.python_check** `if self.pyVersion < "3.6":`

直接使用str进行比较，这种比较方式可能会导致不准确的结果。

比如使用`self.pyVersion = "3.11.3"`直接进行比较，它将返回False，这并不符合我们对版本号的期望。

**Comment by foyaga** [comment]
> **module.Finger.lib.checkenv.CheckEnv.python_check** `if self.pyVersion < "3.6":`
> 
> 直接使用str进行比较，这种比较方式可能会导致不准确的结果。
> 
> 比如使用`self.pyVersion = "3.11.3"`直接进行比较，它将返回False，这并不符合我们对版本号的期望。

现在不会报错了
